# Part 1 Load and Inspect the Data

In [ ]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

df = pd.read_csv("adult-modified.csv")

## display the first 5 rows

In [8]:
df.head()

,age,workclass,education,marital-status,race,sex,hours-per-week,income
0,39,Public,13,Single,White,Male,40,<=50K
1,50,Self-emp,13,Married,White,Male,13,<=50K
2,38,Private,9,Single,White,Male,40,<=50K
3,53,Private,7,Married,Black,Male,40,<=50K
4,28,Private,13,Married,Black,Female,40,<=50K

## Report the number of rows and columns

In [11]:
df.shape

print(f'Rows: {df.shape[0]}')
print(f'Columns: {df.shape[1]}')

Rows: 10000
Columns: 8

## Display the column names and data types

In [12]:
print(df.columns)
print(df.dtypes)

Index(['age', 'workclass', 'education', 'marital-status', 'race', 'sex',
       'hours-per-week', 'income'],
      dtype='str')
age                 str
workclass           str
education         int64
marital-status      str
race                str
sex                 str
hours-per-week    int64
income              str
dtype: object

## Summarize numeric and categorical columns

In [14]:
df.describe(include="all")

,age,workclass,education,marital-status,race,sex,hours-per-week,income
count,10000,10000,10000.000000,10000,10000,10000,10000.000000,10000
unique,72,4,NaN,2,5,2,NaN,2
top,31,Private,NaN,Single,White,Male,NaN,<=50K
freq,284,6947,NaN,5017,8556,6703,NaN,7621
mean,NaN,NaN,10.076600,NaN,NaN,NaN,40.530300,NaN
std,NaN,NaN,2.548172,NaN,NaN,NaN,12.277197,NaN
min,NaN,NaN,1.000000,NaN,NaN,NaN,1.000000,NaN
25%,NaN,NaN,9.000000,NaN,NaN,NaN,40.000000,NaN
50%,NaN,NaN,10.000000,NaN,NaN,NaN,40.000000,NaN
75%,NaN,NaN,12.000000,NaN,NaN,NaN,45.000000,NaN
max,NaN,NaN,16.000000,NaN,NaN,NaN,99.000000,NaN

## What each row represents 
Each row in the dataset represnets one person with their demographic information such as age, workclass, education, marital-status, race, sex, hours-per-week and income. The target variable is income which classifies and individual as making more than or less than 50k

# Part 2 Identity Data Quality Problems

In [7]:
#sum the missing values
df.isna().sum()

age               0
workclass         0
education         0
marital-status    0
race              0
sex               0
hours-per-week    0
income            0
dtype: int64

## Examine the unique frequency counts for 'age' and 'workclass'

In [17]:
df["age"].unique()
df["workclass"].unique()

print(df["age"].value_counts())
print(df["workclass"].value_counts())

age
31    284
35    270
34    268
23    267
33    267
     ...
84      3
82      2
83      2
88      1
85      1
Name: count, Length: 72, dtype: int64
workclass
Private     6947
Public      1317
Self-emp    1148
?            588
Name: count, dtype: int64

## Identify values that represent missing information but are not stored as 'NaN'
Looking at the output above, we can see that in the workclass column that missing values are represented as "?" instead of "NaN".

## Count the affected records and calculate the percentage affected in each column

In [18]:
missing_workclass = (df["workclass"] == "?").sum()

print(missing_workclass)

workclass_percent = (missing_workclass / len(df)) * 100

print(workclass_percent)

588
5.88